# Generated by Django 4.1.7 on 2023-03-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otschedule',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
